let a="Manish Das";
let b="Student's name";
let c="School's name";
let d="Gobardanga Khantura Boys High School";
let e="Roll number-69.";
let f="Obtained grade-A";
let h="Section- B";
console.log("--------------------------------------------------------------------------")
console.log(`               🆁🅴🅿🅾🆁🆃 🅲🅰🆁🅳               `);
console.log(c,"-",d);
console.log(b,"-",a);
console.log("Class-6");
console.log(e);
console.log(h);
console.log("Marks obtained in the subject out of 100");
console.log("Bengali-91/100");
console.log("English-93/100");
console.log("Urdu-92/100");
console.log(f);
console.log("Student is evaluated to the next standard.");
console.log("--------------------------------------------------------------------------");